version: '3'
services:
  scores-db:
    build: ./database/.
    image: michaelgaragaty/wog-scores-db
    environment:
      MYSQL_ROOT_PASSWORD: "wog-score-data"
    ports:
      - '3306:3306'

  wog-score:
    build: .
    image: michaelgaragaty/wog-score
    ports:
      - '8777:5000'
    volumes:
      - ${PWD}/Scores.txt:/app/Scores.txt
    depends_on:
      - scores-db